ボスの追加
Tatsuki5274/stern pull request #115
Opened 2019-04-24 08:03 UTC by tonegawa1124

jsonMapの方はまた別で直すので今の所は気にしないで

2019-04-24 08:54 UTC, Tatsuki5274 requested changes
スコープに問題あり。
可能な限りprivateにするべき。

2019-04-24 08:54 UTC, Tatsuki5274 commented on Hide/BossEnemy.h
> +	void change_angle();
change_angele()は別のメソッドで利用される？
されないのであればprivateにする必要がある。

2019-04-24 08:54 UTC, Tatsuki5274 commented on Hide/BossEnemy.h
>  protected:
メンバがないのであれば書く必要はないと思う

2019-04-24 08:54 UTC, Tatsuki5274 commented on Hide/BossEnemy.h
> +	enum class BossState
クラス外で参照しない列挙体ならprivateにするべき

2019-04-24 10:34 UTC, MR782 approved these changes
動作確認済みpass

2019-04-25 03:30 UTC, Tatsuki5274 commented
コンフリクト改善待ち

2019-04-25 05:36 UTC, Tatsuki5274 commented
指摘点の改善或いは編集がきたらpass

2019-04-25 14:31 UTC, closed without merging