Add2Enemyclass
Tatsuki5274/stern pull request #32
Opened 2019-03-13 11:17 UTC by tonegawa1124

2019-03-13 11:52 UTC, Tatsuki5274 requested changes
問題あり

2019-03-13 11:52 UTC, Tatsuki5274 commented on Hide/Enemy.h
コンストラクタをオーバーロードする理由は？？

2019-03-13 11:52 UTC, Tatsuki5274 commented on Hide/Enemy.cpp
> +	Enmyupdate = new Enemy();
update()は毎フレーム呼ばれる。
これだと毎フレームインスタンス化することになる。
インスタンス化はコンストラクタなど一度しか呼ばれない場所でするべき

2019-03-13 11:52 UTC, Tatsuki5274 commented on Hide/Enemy.h
引数ありコンストラクタが使用されていない。

2019-03-13 23:49 UTC, Tatsuki5274 requested changes
Enemyupdateオブジェクトの使用用途が不明。

2019-03-13 23:49 UTC, Tatsuki5274 commented on Hide/Enemy.cpp
> +	Enmyupdate = new Enemy();
EnemyのコンストラクタでEnemyインスタンス化する設計ではなかったはず

2019-03-13 23:49 UTC, Tatsuki5274 commented on Hide/Enemy.cpp
> +	Enmyupdate->attack();
Enemyupdate->method()
ではなく
this->method()
なのでは？
(thisは省略可能)

2019-03-14 03:22 UTC, Tatsuki5274 requested changes
設計と異なるコードが含まれているため改善が必要。

2019-03-14 03:22 UTC, Tatsuki5274 commented on Hide/Enemy.cpp
> +
move()は仮想関数だから実体の定義は不要なのでは？

2019-03-14 03:22 UTC, Tatsuki5274 commented on Hide/Enemy.h
> -
Enemyクラスのコンストラクタは設計によるとint型引数を3つ受け取ることになっているから削除されたコードのほうが正しい。

2019-03-14 10:35 UTC, Tatsuki5274 requested changes
もう少し改善が必要

2019-03-14 10:35 UTC, Tatsuki5274 commented on Hide/Enemy.cpp
> +	damage = 0;
コンストラクタの引数が利用されていない！
これだと引数なしでもよくなる！

2019-03-15 04:59 UTC, Tatsuki5274 requested changes
メンバのスコープに問題あり！
あとこれだけ！

2019-03-15 04:59 UTC, Tatsuki5274 commented on Hide/Enemy.h
>  public :
lifeやdamaged、gravityはpublicメンバにするべきではない。

2019-03-16 05:47 UTC, MR782 reviewed
見た感じ問題はなさそう

2019-03-16 08:51 UTC, Tatsuki5274 reviewed
move()の定義が必要か曖昧。。。

2019-03-16 08:51 UTC, Tatsuki5274 commented on Hide/Enemy.h
> +	//�����o�[�֐�
デフォルトのアクセシビリティがprivateなので問題はないけれど、１行記述をして欲しかった、、、
必須ではないから無視でもok

2019-03-16 12:37 UTC, Tatsuki5274 approved these changes
問題なし

2019-03-17 04:39 UTC, merged