Enemysubclass
Tatsuki5274/stern pull request #37
Opened 2019-03-18 03:11 UTC by tonegawa1124

walkingEnemyやflyingEnemy

2019-03-19 00:27 UTC, MR782 reviewed
要検討

2019-03-19 07:33 UTC, Tatsuki5274 approved these changes
スコープに問題あり

2019-03-19 07:33 UTC, Tatsuki5274 commented on Hide/FlyingEnemy.h
> +	enum FlyingState
・enumではなくenum classで定義するべき。
・enum をクラスのメンバにすると他で利用できなくなってしまう。

2019-03-19 07:33 UTC, Tatsuki5274 commented on Hide/WalkingEnemy.h
> +	enum WakingState
同上。

2019-03-19 07:33 UTC, Tatsuki5274 commented on Hide/WalkingEnemy.h
> +	WakingState wakingstate;
・wakingではなくwalkingなのでは？
・walkingstateはpublicメンバにするべきではない。

2019-03-19 07:33 UTC, Tatsuki5274 requested changes
改善が必要

2019-03-24 07:13 UTC, Tatsuki5274 requested changes
move()に問題あり

2019-03-24 07:13 UTC, Tatsuki5274 commented on Hide/WalkingEnemy.cpp
> +	switch(wakingstate)
右にしか動かないんじゃ・・・

2019-03-24 07:13 UTC, Tatsuki5274 commented on Hide/FlyingEnemy.h
> +		stay,
最後の項目のコンマはエラーは不要なのでは？

2019-03-25 05:20 UTC, MR782 reviewed
WalkingEnemyは壁にぶつかったら反転するんじゃなかったっけ？
enumClassはクラス外に定義したほうがいいんじゃないかな?

2019-03-26 05:20 UTC, MR782 approved these changes
pass

2019-03-26 07:05 UTC, Tatsuki5274 approved these changes

2019-03-26 07:05 UTC, merged