starのexercise導入とその近辺修正
Tatsuki5274/stern pull request #89
Opened 2019-04-04 10:21 UTC by iipyon

デバック用にマップや星のステータスをいじってる
バーチャル関数周りを合ってるかどうか確かめてほしい
phisicと同じように作っているけどもphisicと違う動作をしていてキレてる

2019-04-04 10:29 UTC, MR782 reviewed
virtual でexercise書いてあってPhsic.cppとStarの両方で処理が書いてあるけどどっちが使われているの?

2019-04-04 11:15 UTC, iipyon commented
phisicのexerciseはプレイヤーや敵に反映されてて starにあるexerciseはスターに反映されてる

2019-04-04 13:23 UTC, Tatsuki5274 requested changes
publicメンバやprotectedメンバが明らかに多いためスコープの見直しが必要だと思う。
例えばexercise()はサブクラスのupdate()で呼び出すため、protectedで十分で、メソッドもプロパティもprivateにするほど品質が良いと言える。
virtual周りの記述はGood！

2019-04-04 13:23 UTC, Tatsuki5274 commented on Hide/Star.h
> +	Point starpoint;
starpointを処理の中で一時的に利用するだけであればプロパティにする必要はないのでは？

2019-04-04 13:23 UTC, Tatsuki5274 commented on Hide/Star.h
>  	Point enemy_point;
enemy_pointに関しては変更点に含まれないけれど、starpointと同様に一時的な利用であればプロパティにする必要はない。

2019-04-04 13:29 UTC, iipyon commented
了解、ノーマルスターのアップデートにある程度目処が立ったら直しとく

2019-04-04 14:17 UTC, iipyon commented
ノーマルスターアップデート周りを更新したやつをマージしたんでそっちもチェックよろしく
phisicにスラックで言った変更も加えてある
マップの変更は誤差

2019-04-05 02:04 UTC, Tatsuki5274 approved these changes
pass

2019-04-05 02:04 UTC, merged